---
abstract: 'Daemon handling XML-SOAP'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-SOAP-Daemon
no_index:
  directory:
    - t
    - inc
requires:
  Log::Report: 0.9
  Test::More: 0.54
  Time::HiRes: 0
  XML::Compile: 1.26
  XML::Compile::Cache: 0.991
  XML::Compile::SOAP: 3.00
  XML::Compile::Tester: 0.90
  XML::Compile::WSA: 0.9
version: 3.07
